### ISSUE TITLE
httpd not automatically started in Fedora VM

### ISSUE THREAD

**Issue by advornic** [arista-eosplus/packer-ztpserver#14]
Workaround is to start it manually form bash:

"sudo service httpd start"

**Comment by phil-arista** [comment]
This is by design so that people can just use standalone mode (since wsgi is probably more advanced). Are you proposing we enable this by default?

Note: you'd also want to enable it so it starts automatically on subsequent reboots
  Systemctl enable httpd

**Comment by advornic** [comment]
Yes, I would enable this by default.
