### ISSUE TITLE
Failed ZTP Server install on VMware Workstation 10

### ISSUE THREAD

**Issue by mprior1** [arista-eosplus/packer-ztpserver#24]
Install failed with the following error:

1 error(s) decoding:

* cannot parse 'disk_size' as uint: strconv.ParseUint: parsing "'7000'": invalid
 syntax
Return code:1
Packer install failed!!!

**Comment by mprior1** [comment]
This failed using the Python scripted Packer install.  Syntax used is 'C:\Python
27\python.exe ./create-ztpserver.py -H vmware -o fedora --vmname ztp-server1'

**Comment by phil-arista** [comment]
Hello - sorry about that issue.  It should be fixed now.  Let me know if you hit any other issues and I'm happy to help.

**Comment by mprior1** [comment]
Thanks you Philip this is fixed now.

Regards

Mark Prior  CCIE #9096
Technical Architect
Consultancy Practice – Network & Security

Computacenter (UK) Ltd
1 Thames Valley Park
Reading,
Berkshire RG6 1PT

T: 0118 935 6000
M: 07801 452764
Mobex: 452764

E:  mark.prior@computacenter.com<mailto:mark.prior@computacenter.com>
W: www.computacenter.com<https://urldefense.proofpoint.com/v1/url?u=http://www.computacenter.com/&k=oIvRg1%2BdGAgOoM1BIlLLqw%3D%3D%0A&r=Oa8ScBwkizSTnk9ONg0e2w%3D%3D%0A&m=mMHAv3f6eKXg5gt8UmlTqfEVKM%2F9w6VFQqeo5e%2BktUk%3D%0A&s=5d0df0a720d845b354e7895bc77d97e9e4d9c16c9bbddd828e4875b2bcd325f2>
