### ISSUE TITLE
Install failing of automatic vEOS node creation using Packer

### ISSUE THREAD

**Issue by mprior1** [arista-eosplus/packer-ztpserver#25]
I am trying to install vEOS nodes using Python and Packer with the syntax 'c:\Python27\python
.exe ./create-veos.py -H vmware' and am getting the following error - Executing command:C:\Users\mprior\packer-bin\packer build --parallel=false  -var
 'boot_time=2m30s' -var 'name=20150409_161825' vEOS.json
'"C:\Users\mprior\packer-bin\packer build --parallel=false  -var 'boot_time=2m30
s' -var 'name=20150409_161825' vEOS.json"' is not recognized as an internal or e
xternal command,
operable program or batch file.
Return code:1
Packer install failed!!!

Can you help please?

**Comment by phil-arista** [comment]
Hello - try to pull the latest from master and try again.  It should be fixed.
Thanks
