### ISSUE TITLE
Big red button

### ISSUE THREAD

**Issue by advornic** [arista-eosplus/packer-ztpserver#4]
Instead of:
 - a set of instructions about how to create/fix the vboxnets (for example) (1)
 - another set of instructions on how to run packer (2)

Why not have a simple script which does (1) automatically for you and them starts packer (and you forward the command line arguments from this script to packer). We should still document what happens behind the scenes, but sounds like exactly the the kind of process which could/should be automated.

Basically, have a big red button instead of two - there is really no point in breaking the whole VM creation process in two steps, which is probably only an artefact of packer not support doing (1) for now (?).

Plus, a wise man once told me that a script calling other scripts is cool. :)

Same comment for vEOS and Vmware (instead of VirtualBox). 

Extra - why not include this as well in the same process:
[ - a set of instructions on how to install packer (0)]
?

**Comment by phil-arista** [comment]
This is almost finished.  Tracked in https://github.com/arista-eosplus/packer-ztpserver/tree/feature-bigRedButton
